### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asim** [micro/chat#7]
Non comprehensive list of things todo

- [x] Password reset
- [x] Password confirmation
- [x] Name change
- [x] Email change
- [x] Remove self from group
- [x] Remove a user from the group (e.g hi thee)
- [x] Remove invite for user
- [x] Member admin / settings
- [x] Private audio/video
- [x] Edit room names or delete
- [x] Websockets not rendering
- [x] Selecting video then audio removes video cam
- [x] When width is less than 600px collapse the menu
- [x] Mobile rendering / small screen optimisation
- [x] No signup button is present on mobile / small width screen
- [x] View same room / chat on refresh
- [ ] ~~Disabling speaker doesn't turn off sound~~
- [x] Changing title or related things removes video
- [x] Animate double click zoom of video
- [x] Burger menu sidebar on mobile (less than 600px)
- [ ] Drop down menu for groups
- [x] Limit group sizes to 24
- [x] Lowercase emails so we dedupe e.g Asim@m3o.com vs asim@m3o.com
- [x] Invite links; add an invite url with invites and /signup link with prefill
- [ ] Guests / guest rooms; provide one time link to allow non members to chat
- [ ] video shows up as a square in Safari
- [ ] invite emails are from "support"
- [ ] send message needs a button to send the message
- [ ] message box is not displayed on mobile without scrolling
- [ ] messages do not auto scroll to show latest
- [ ] messages do not display date if older than today
- [ ] Move to stream only text chat (no storage)
- [ ] Oauth2 single sign on: google/github
- [ ] Passwordless login e.g magic link email
- [ ] Signup onboarding flow; create groups, invite friends, etc
- [ ] text/audio/video notes for async consumption
- [ ] scheduled events and reminders
- [ ] replace landing page screenshots with more "photogenic" people
- [ ] make distributed itself embeddable anywhere on the web
- [ ] Add ability to create video filters / overlays
- [ ] Send web and email notifications for new messages
- [ ] Strip payments from gifs

Twilio Dave's feedback (Direct of product, developer experience)

- [x] Add emoji button inside send message box
- [x] Add double click to expand a user's video
- [ ] Add 60 minute video time limit + topup shared credit / £1/month (TBD)
- [ ] Fix mobile rendering
- [ ] Add screen share support
- [x] Add shared whiteboard canvas

Commands / Services

- [x] Whiteboard (canvas)
- [ ] Ping (play bell and push notification)
- [ ] Make everything a command/message
    - invite foo@bar.com
    - camera on/off
    - mic on/off
